/** Enterprise portal module tiles — only VCare Portal is active. */
export const enterpriseModules = [
  {
    id: 'vcare-portal',
    title: 'VCare Portal',
    description: 'Clinic operations — appointments, clinical workflows, billing, inventory, finance, and role-based workspaces.',
    icon: 'heart-pulse',
    href: '/dashboard/my-tasks',
    active: true,
  },
  {
    id: 'finance',
    title: 'Finance',
    description: 'Chart of accounts, day close, GST exports, collections, and ledger management.',
    icon: 'wallet',
    active: false,
  },
  {
    id: 'hrms',
    title: 'HRMS',
    description: 'Employee records, designations, organogram, and HR workflows.',
    icon: 'users',
    active: false,
  },
  {
    id: 'compliance',
    title: 'Compliance',
    description: 'Regulatory standards, audit trails, and policy adherence across branches.',
    icon: 'shield',
    active: false,
  },
  {
    id: 'approvals',
    title: 'Approvals',
    description: 'Cross-department request routing, authorizations, and workflow sign-offs.',
    icon: 'clipboard',
    active: false,
  },
  {
    id: 'clinical',
    title: 'Clinical Operations',
    description: 'Treatment plans, procedures, consent forms, and clinical consumption tracking.',
    icon: 'stethoscope',
    active: false,
  },
  {
    id: 'inventory',
    title: 'Inventory & Supply',
    description: 'Stock management, indents, warehouse dispatch, and factory inward flows.',
    icon: 'boxes',
    active: false,
  },
  {
    id: 'procurement',
    title: 'Procurement',
    description: 'Purchase orders, GRN, asset procurement, and vendor management.',
    icon: 'truck',
    active: false,
  },
  {
    id: 'callcenter',
    title: 'Call Center',
    description: 'Lead management, follow-ups, appointment booking, and dialer integration.',
    icon: 'phone',
    active: false,
  },
  {
    id: 'reports',
    title: 'Reports & Analytics',
    description: 'Sales, GST, incentives, branch comparison, and executive dashboards.',
    icon: 'chart',
    active: false,
  },
  {
    id: 'it-admin',
    title: 'IT Administration',
    description: 'System access, IP whitelist, integrations, and platform configuration.',
    icon: 'settings',
    active: false,
  },
];
